### ISSUE TITLE
Refine Ordinal Legends

### ISSUE THREAD

**Issue by seemantk** [cfinst/cfinst.github.io#185]
Now that the dataset is more complete -- visually, we can now discern various places where the visualization is inadvertently adding noise.

# Color Scheme Consistency
As a team, we put a lot of thought into the threshold colors because contribution-limits was the first section we did.  Thus, there's a sense of consistency in those scales/legends.  Some notes

## 2 Shades of Red for starkly opposed options
(Like "Prohibited" vs "Unlimited"  in threshold legends)
In the ordinal legends/scales, the two starkly opposed options are "Yes" and "No"

## Many blue hues for categorical and/or nuanced options
(Like finite number ranges in threshold legends)

We researched several shades of blue (7 or so?) for this purpose
Categorical things like "mid-cycle" "full cycle" items or "Inoperative" items would better fit within the blue scheme
 
## Grays for N/A-like answers (i.e., not applicable, because...)
Thus, things like "N/A", "disclose if" (read: "n/a unless"), and "voluntary" (read: "n/a if I want") are good shades of gray candidates

## Black for "I don't know"  (ie: Missing Data)
This is good for both debugging & highlighting.

### Extra/Unneeded legend items

This is especially true in Disclosure section which, as a combination of all the things, including options that don't appear in the map or atlas result in legends that are haphazard/chaotic.
Perhaps there's a need for an additional named legend in legends.yml?

**Comment by seemantk** [comment]
@curran, @bglavin: would greatly appreciate your thoughts

**Comment by curran** [comment]
@seemantk I have also noticed the pain of "Extra/Unneeded legend items". One idea I had was that maybe we could add a "prune" option to the legend configs, and in this case we can apply a filter to the legend items such that *only* values that actually appear in the data (somewhere in the grid) end up appearing in the legend.

**Comment by curran** [comment]
I showed this project to a Professor in Data Visualization that I've known for years, and the only advice he had was something like "Better not to overload the colors, for cognative stability". Meaning that, a certain shade of blue should *always* mean the same thing, across tabs, and a color should never be re-used in different tabs to mean different things.

I sort of thought it would be too much work, and perhaps would force us into using a variety of colors that might break with the CFI theme, but since we're revisiting the legends at a higher level now, this thought might be worth considering.

As one example, the thresholds in Contribution Limits can stay the same as they are, but the lower-valued thresholds in the Disclosure should be shades of *a different hue* (maybe more green-ish or something).

Also, we'd need to take stock of all possible non-numeric values across all tabs, and assign each one to a unique color.

**Comment by curran** [comment]
@seemantk The post above almost reads more like a "Style Guide", which is awesome.

That got me thinking that we could potentially leverage some existing style guides for dataviz, even if it's just mining them for nice thought-out colors.

Here's a big list of dataviz style guides https://policyviz.com/2016/11/30/style-guides/

**Comment by curran** [comment]
@seemantk One implication of globally unique colors is that we could potentially use a single global color scale! The thresholds would need to be pre-computed on the data values (rather than using a D3 Threshold scale), but it could totally work. That would give us the additional benefit of being able to configure all the colors in one place (one .yml). Food for thought...

**Comment by seemantk** [comment]
@curran I very much concur.

**Comment by seemantk** [comment]
pruning of legends is tracked in #196

**Comment by curran** [comment]
Potentially useful http://paletton.com

**Comment by grinstein** [comment]
Very neat

Georges Grinstein
Research Professor - Data Visualization and Visual Analytics
Center for Data Science
College of Information and Computer Sciences
University of Massachusetts Amherst 
Amherst MA 01003
Email: ggrinstein@cs.umass.edu <mailto:ggrinstein@cs.umass.edu>
Cell: 508-331-8161



On Apr 6, 2017, at 11:57 AM, Curran Kelleher <notifications@github.com <mailto:notifications@github.com>> wrote:

Potentially useful http://paletton.com <https://urldefense.proofpoint.com/v2/url?u=http-3A__paletton.com&d=DgMCaQ&c=lqHimbpwJeF7VTDNof4ddl8H-RbXeAdbMI2MFE1TXqA&r=_Wo3dC0U8OQ2lgQWo-k-bYXxDs9VVlFMwstZYCOp72U&m=vaFeVX6Dxs_G0VM3-6aKdw2MrTu0zw2kqhl1CQQVuQ8&s=nYMafX8L1oDjiSmoMA6K_HYDKpPSv_DXLoe1eYq0Bfo&e=>
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_cfinst_cfinst.github.io_issues_185-23issuecomment-2D292220475&d=DgMCaQ&c=lqHimbpwJeF7VTDNof4ddl8H-RbXeAdbMI2MFE1TXqA&r=_Wo3dC0U8OQ2lgQWo-k-bYXxDs9VVlFMwstZYCOp72U&m=vaFeVX6Dxs_G0VM3-6aKdw2MrTu0zw2kqhl1CQQVuQ8&s=mnCQRvMMmF60y-4gczkEQ0mZRCl7XHjAj_pdLoPf1A8&e=>, or mute the thread <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AAw3SoZh6zrsRaoNj1l9bU5vQcxCwBImks5rtQt2gaJpZM4MnafJ&d=DgMCaQ&c=lqHimbpwJeF7VTDNof4ddl8H-RbXeAdbMI2MFE1TXqA&r=_Wo3dC0U8OQ2lgQWo-k-bYXxDs9VVlFMwstZYCOp72U&m=vaFeVX6Dxs_G0VM3-6aKdw2MrTu0zw2kqhl1CQQVuQ8&s=S_wuoq7O5BE-EiKxAbtEq30182HOrUa79nJtfz7yMfk&e=>.




Georges Grinstein
Research Professor - Data Visualization and Visual Analytics
Center for Data Science
College of Information and Computer Sciences
University of Massachusetts Amherst 
Amherst MA 01003
Email: ggrinstein@cs.umass.edu <mailto:ggrinstein@cs.umass.edu>
Cell: 508-331-8161

**Comment by curran** [comment]
@grinstein Nice to see you chime in here! We're going all-in with your suggestion on not overloading colors. Thanks again for your input there.

Another neat tool I came across today https://vis4.net/labs/multihue/ :
![image](https://cloud.githubusercontent.com/assets/68416/24788925/e2bc8896-1b8d-11e7-98ba-22af0ef8ddf9.png)

while reading this article on color https://blogs.adobe.com/creativecloud/the-power-of-the-palette-why-color-is-key-in-data-visualization-and-how-to-use-it/

**Comment by curran** [comment]
Copying over the comprehensive color palette categories and values from @seemantk 's email thread here, for discussion/iteration:

Contribution Limits (normal):

 * Prohibited
 * $1,000 or less
 * $1,001 - $2,500
 * $2,501 - $5,000
 * $5,001 - $10,000
 * $10,000 or greater
 * Unlimited

Contribution Limits (high) [changed per our call]
Prohibited

 * $2,500 or less
 * $2,501 - $5,000
 * $5,001 - $10,000
 * $10,001 - $50,000
 * $50,000 or greater
 * Unlimited

Disclosure Thresholds

 * $0
 * $50 or less
 * $51 - $100
 * $101 - $200
 * $201 - $500
 * More than $500
 * No Limit

Disclosure Thresholds (Aggregated)

 * Prohibited
 * $1000 or less
 * $1,001 - $2,500
 * $2,501 - $5,000
 * $5,001 - $10,000
 * More than $10000
 * Unlimited

Miscellaneous Disclosure legend items:

 * N/A
 * Voluntary
 * Disclose donor if >$250

Cycles (Disclosures & Other Restrictions)

 * Changed Mid-Cycle
 * Inoperative Mid-Cycle
 * Inoperative Whole Cycle

Public Financing

 * None
 * Partial Grant
 * Matching Funds
 * Mixed
 * Full Public Financing

Public Financing (taxes):

 * None
 * Refund
 * Tax Credit
 * Tax Deduction

**Comment by curran** [comment]
One thought I have here is that we may be able to unify the thresholds for contribution limits, rather than having different sets of thresholds for different fields. For this we'd need a scale with 6 gradations, which is probably doable.

**Comment by curran** [comment]
I've gone through and done a full pass at the color pallette in #208 . Here's what's in use there:

![image](https://cloud.githubusercontent.com/assets/68416/24798792/8d5e97f4-1bb5-11e7-8ac9-46a99c0cfe91.png) 
![image](https://cloud.githubusercontent.com/assets/68416/24798798/98e1e518-1bb5-11e7-83ea-ed1a7437a143.png) 
![image](https://cloud.githubusercontent.com/assets/68416/24798812/b02328ea-1bb5-11e7-8bac-a464937e9d9a.png) 
![image](https://cloud.githubusercontent.com/assets/68416/24798821/bae636dc-1bb5-11e7-9b78-9943cb68c3bc.png) 
![image](https://cloud.githubusercontent.com/assets/68416/24798834/c92b6924-1bb5-11e7-8b58-0163a2f89161.png) 
![image](https://cloud.githubusercontent.com/assets/68416/24798843/d6bbc6f6-1bb5-11e7-9ad6-822fe94c3e9a.png)

**Comment by curran** [comment]
Here's a sampling of how this palette plays out in the visualizations:

![image](https://cloud.githubusercontent.com/assets/68416/24799943/9c161b4a-1bbb-11e7-8e45-19fe46c5dbe3.png)

![image](https://cloud.githubusercontent.com/assets/68416/24799965/b5b0eb20-1bbb-11e7-8ba7-05de7c89c9eb.png)

![image](https://cloud.githubusercontent.com/assets/68416/24799990/cd402ef4-1bbb-11e7-99af-41f83ff7d095.png)

![image](https://cloud.githubusercontent.com/assets/68416/24800021/e7de7694-1bbb-11e7-87dd-aa148c36986d.png)

![image](https://cloud.githubusercontent.com/assets/68416/24800055/01ee84ac-1bbc-11e7-9f84-651d80646a42.png)

![image](https://cloud.githubusercontent.com/assets/68416/24800069/160ef098-1bbc-11e7-8b78-e3459a94a5b1.png)

**Comment by curran** [comment]
![image](https://cloud.githubusercontent.com/assets/68416/24800138/747f7f62-1bbc-11e7-9bf9-e72038007c96.png)

**Comment by curran** [comment]
Copying over some TODOs into here from email:

 * [ ] Change the brown used for all "no", “not allowed” and "none" answers to #8B4513

 * [ ] We would like to see a gradation in blues for the contribution limit categories. Include "unlimited" in the same color scale, eliminating the red.  That would give us a total of seven (7) data classes
​ with the following HEX values:
#eff3ff
#c6dbef
#9ecae1
#6baed6
#4292c6
#2171b5
#084594

Disclosure thresholds (upper middle):

 * [ ] Collapse "201-$500" and "More than $500" into a single category that will read "More than $200.
 * [ ] Once you do this, you will have one less category. Use dark purple for $0 and progressively lighter shades going up for the next four steps. $0 needs to be portrayed as part of the gradient.
 
 * [ ] Change the "Public Finance" values to the following HEX values:
#618685
#deeaee
#c94c4c
#b1cbbb
 
 * [ ] Tax credit, deductions, refunds: Change to the following HEX values:
#e6550d for refund
#fdae6b for tax credit
#fee6ce for tax deduction

**Comment by curran** [comment]
Closed in **Cognify** #208

**Comment by curran** [comment]
Related discussion in https://github.com/cfinst/cfinst.github.io/issues/247

Also http://labs.abeautifulsite.net/jquery-minicolors/ is a great tool for picking colors.
