### ISSUE TITLE
Usability: Link legend items to map/atlas highlighting

### ISSUE THREAD

**Issue by seemantk** [cfinst/cfinst.github.io#186]
It would greatly enhance usability to be able to see, very clearly, **which items** on the map/grid fall in a category shown by the legend.

@curran, looking to your expertise: how reasonable/unreasonable is the level of effort required for this?

**Comment by curran** [comment]
Oh totally. I've had this thought as well.

Here's an example that does something similar, using an overlay https://bl.ocks.org/curran/805413fb3b2efaada1ce

To accomplish this in this project, my initial thoughts are

 * One way to do it is to have an "overlay rectangle" that appears on top of the map and the grid, that "grays out" everything other than the items that fall into the hovered legend item.
 * We'd want to have the rendering logic abstracted into a function in such a way that we can call it multiple times, passing *different selections*.

As an alternative, I wonder if we could simply use the highlighting infrastructure that we already have in place. If I recall correctly, we could pass an array of "highlighted elements" rather than just a single one. This may be the path of least resistance. It may be a win from the UX perspective too, because users are already seeing the yellow highlight, and having more yellow highlights appear on legend hover would be less of a cognitive shock than the overlay approach.

**Comment by curran** [comment]
Another random related idea that should be its own issue if we choose to do it: The legend rectangles could be sized by the count of states that fall into them, making the legend into a horizontal bar chart.
