### ISSUE TITLE
Updates not taking

### ISSUE THREAD

**Issue by bglavin** [cfinst/cfinst.github.io#245]
I having an issue getting some updates to show on the site.

I added a new color in colors.yml and changed the reference in the legend, but it is not picking up. I then tried changing the reference to an existing color and it would not pick that up either. 

Also, I switched the order (ordinal) under disclosure legends and that is not showing either. 

Any thoughts?

**Comment by curran** [comment]
Hi @bglavin , thanks for filing an issue about this. I researched recent commits and found this:
![image](https://cloud.githubusercontent.com/assets/68416/26382905/a54c7414-3ffd-11e7-9714-01a4ec069209.png)

It turns out that a change cause the Jekyll build to fail, because a syntax error in one of the YML files.

Will investigate how we can fix it.

**Comment by curran** [comment]
@bglavin This is fixed in #246 - it turned out to be a syntax error with respect to white space.

**Comment by curran** [comment]
We can tell that the build succeeds now by the green check mark next to the most recent commit (in the [recent commits view](https://github.com/cfinst/cfinst.github.io/commits/master)):

![image](https://cloud.githubusercontent.com/assets/68416/26383144/38a707be-3fff-11e7-8a39-116db4a929c6.png)
